### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by leogean3**
requirements file for python

### CODE REVIEW

**Comment by KevinShook** [comment]
Thanks very much.
One final question.
I see that the file says
wxPython==4.1.0

Wouldn't it be a good idea to change it to
wxPython>=4.1.0
to prevent version problems every time wxPython is changed?

If so, I can change it.

K
---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Ah yes, you are right, >=4.1.0 is better.

Thanks a lot for your attention,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月3日 14:11
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Create requirements.txt (#40)


Thanks very much.
One final question.
I see that the file says
wxPython==4.1.0

Wouldn't it be a good idea to change it to
wxPython>=4.1.0
to prevent version problems every time wxPython is changed?

If so, I can change it.

K
---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
No problem, it's now fixed.
On to the next one!
Issue #18
https://github.com/CentreForHydrology/WDPM/issues/18
The reviewer suggests using a linter.
I ran the code through pylint and got the attched output.
Most of the warnings are just to do with spacing, but we should still take care of them.

Thanks,

K
---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
There are just a couple more issues to take care of.
They overlap a lot with #18
https://github.com/CentreForHydrology/WDPM/issues/12
https://github.com/CentreForHydrology/WDPM/issues/14
[https://avatars.githubusercontent.com/u/25204882?s=400&v=4]<https://github.com/CentreForHydrology/WDPM/issues/14>
Abstract UI control ・ Issue #14 ・ CentreForHydrology/WDPM<https://github.com/CentreForHydrology/WDPM/issues/14>
These lines show a large amount of duplication. This could be reduced by looping over a list of components to enable/disable. It also suggests that perhaps the UI should be broken into separate con...
github.com
Once these are finished, we're pretty much done.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Hi Kevin,

Copy that, I will look into those issues.

Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月4日 10:02
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Create requirements.txt (#40)


There are just a couple more issues to take care of.
They overlap a lot with #18
https://github.com/CentreForHydrology/WDPM/issues/12
https://github.com/CentreForHydrology/WDPM/issues/14
[https://avatars.githubusercontent.com/u/25204882?s=400&v=4]<https://github.com/CentreForHydrology/WDPM/issues/14>
Abstract UI control ・ Issue #14 ・ CentreForHydrology/WDPM<https://github.com/CentreForHydrology/WDPM/issues/14>
These lines show a large amount of duplication. This could be reduced by looping over a list of components to enable/disable. It also suggests that perhaps the UI should be broken into separate con...
github.com
Once these are finished, we're pretty much done.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
Thanks very much.
Please let me know if there's anything that I can do to help.
We're getting very close to being finished.
After these are done, I just need Ray and John to sign off.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Pull request merged**
