### PR TITLE
Update WDPM.py

### PR DESCRIPTION
**Pull request by leogean3**
Just want to backup the code here. The pylint score is 8.73 for this version. keep fixing it

### CODE REVIEW

**Comment by KevinShook** [comment]
Nice work!

**Comment by KevinShook** [comment]
Do you want me to merge it into a branch for you?

**Comment by leogean3** [comment]
Ah yes, I think that could be helpful. So that I can compare the difference with this version next time. Thanks a lot:)

Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月8日 14:36
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Update WDPM.py (#43)

CAUTION: External to USask. Verify sender and use caution with links and attachments. Forward suspicious emails to phishing@usask.ca


Do you want me to merge it into a branch for you?

―

**Comment by KevinShook** [comment]
Merged into branch `testing`

**Pull request merged**
