### PR TITLE
Update WDPM.py

### PR DESCRIPTION
**Pull request by leogean3**
The code has been rated at 9.72/10 by pylint. For the remaining warning. Some of them relavant to the code structure. The body of the "size class" is too big. I am not sure if we can just leave it as it is. Because re-write this part might need big modification to the code. For the others, I haven't got solutions. Sometimes after get rid of the pylint warning, the code cannot work properly. I will further look into it.

### CODE REVIEW

**Comment by KevinShook** [comment]
There are conflicts between this version and the most recent version in GitHub of WDPM.py.
Did you base your changes on the most recent version?
It will take quite a lot of work to fix the conflicts.
It would help a lot if you could fix them on your end by basing your changes on the testing branch

**Comment by KevinShook** [comment]
I will try to fix it. Please don't make any changes yet.
Once I've fixed the branch, you will need to check it out to make sure that it is correct.

**Comment by leogean3** [comment]
Ah, I see. Sorry for that. I can take care of that if it is not convenient from your end. I can directly copy and paste the full code to the lastest version code

Best regards,
Leo


获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KevinShook** [comment]
Hi Leo
I've already started, so I need to fix it.
I'll let you know when it's fixed.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
I've pushed the changes, but they cause errors.
I think it might be faster for you to pull the master, make changes and submit a pull request.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Sure, I will work on that. Could you please tell me the directory of the latest version code (the code I supposed to change based on)? I was originally modify based on the /src/WDPM.py.  But seems this code is uploaded two days ago.

Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月9日 11:08
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Update WDPM.py (#44)


I've pushed the changes, but they cause errors.
I think it might be faster for you to pull the master, make changes and submit a pull request.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Ah, I think I find it. It should be under tree/testing/src right?......
________________________________
发件人: Liu, Tonghe <tol924@mail.usask.ca>
发送时间: 2021年2月9日 11:11
收件人: CentreForHydrology/WDPM <reply@reply.github.com>
主题: 回复: [CentreForHydrology/WDPM] Update WDPM.py (#44)

Sure, I will work on that. Could you please tell me the directory of the latest version code (the code I supposed to change based on)? I was originally modify based on the /src/WDPM.py.  But seems this code is uploaded two days ago.

Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月9日 11:08
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Update WDPM.py (#44)


I've pushed the changes, but they cause errors.
I think it might be faster for you to pull the master, make changes and submit a pull request.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Pull request merged**
