### PR TITLE
Update WDPM.py

### PR DESCRIPTION
**Pull request by leogean3**
re-group the import

### CODE REVIEW

**Comment by KevinShook** [comment]
Hi Leo,
As I had said there are many regressions in this version. It looks like you based your changes on an old, incorrect version of the code. Please do a diff of your new version with the current version before making a pull request.
Check lines 73, 168, 224, 245, 750 etc.
In all cases your new version is replacing correct text with incorrect text.

**Comment by leogean3** [comment]
Ah sorry for that, I pull the request again. This time should be correct. For the modification from 750, The code about the "textfile" function is the most up-to-date version. The original code on the github does not use a solver for windows, which is added in this version. Please check.

Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月2日 10:06
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Update WDPM.py (#34)

CAUTION: External to USask. Verify sender and use caution with links and attachments. Forward suspicious emails to phishing@usask.ca


Hi Leo,
As I had said there are many regressions in this version. It looks like you based your changes on an old, incorrect version of the code. Please do a diff of your new version with the current version before making a pull request.
Check lines 73, 168, 224, 245, 750 etc.
In all cases your new version is replacing correct text with incorrect text.

―

**Comment by KevinShook** [comment]
Thanks very much. I will put it in a new branch for testing.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
Hi Leo
I merged in the pull request it looks good.
Now for the next issue:
https://github.com/CentreForHydrology/WDPM/issues/11

I see that the large comment blocks are removed, but
some lines are still commented out. These should be removed.
Also, I think it would be a good idea to put in some more comments.
We especially need some  at the top of
the program identifying who created it, the licence etc.

Thanks,

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Sure I will handle that. For the license, can I just copy the text in the GUI, which is:

Wetland DEM Ponding Model version 2.0
Copyright (c) 2010, 2012, 2014, 2020 Kevin Shook, Centre for Hydrology
Developed by Oluwaseun Sharomi, Raymond Spiteri and Tonghe Liu
Numerical Simulation Laboratory, University of Saskatchewan.

--------------------------------------------------------------------

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

This program adds water to an ArcGIS ASCII file of water runoff
and redistributes water over the DEM
From the algorithm of Shapiro, M., & Westervelt, J. (1992).
An Algebra for GIS and Image Processing (pp. 1-22).

Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月2日 11:09
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Update WDPM.py (#34)


Hi Leo
I merged in the pull request it looks good.
Now for the next issue:
https://github.com/CentreForHydrology/WDPM/issues/11

I see that the large comment blocks are removed, but
some lines are still commented out. These should be removed.
Also, I think it would be a good idea to put in some more comments.
We especially need some at the top of
the program identifying who created it, the licence etc.

Thanks,

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
That's great, thanks.
K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
Also, I was just looking at this one:
https://github.com/CentreForHydrology/WDPM/issues/13

Looks like we need some more comments here as well.

Thanks,
K
[https://avatars.githubusercontent.com/u/25204882?s=400&v=4]<https://github.com/CentreForHydrology/WDPM/issues/13>
Add comments to UI generation ・ Issue #13 ・ CentreForHydrology/WDPM<https://github.com/CentreForHydrology/WDPM/issues/13>
This section is pretty dense. White space coupled with appropriate comments would make its maintenance easier. openjournals/joss-reviews#2276
github.com


---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Hi Kevin,

I pull a request yesterday to manage the comments, and remove some redundant functions.  Please have a look!

Best regards,
Leo

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KevinShook** [comment]
Thanks very much! I'll get on it right away.
K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
Hi Leo
I fixed a couple of minor typos and merged the code in
2 minor things

  1.  What is this line and why is it commented? It should be explained better or removed,. Can I delete it?
Line 616:     #self.redir.write(readstuff)
  2.  There was a file included called WDPM-GUI.txt. I deleted it.


Thanks,
K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Ah yes, I missed them. Thanks for your attention.

Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月3日 9:35
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Update WDPM.py (#34)


Hi Leo
I fixed a couple of minor typos and merged the code in
2 minor things

1. What is this line and why is it commented? It should be explained better or removed,. Can I delete it?
Line 616: #self.redir.write(readstuff)
2. There was a file included called WDPM-GUI.txt. I deleted it.


Thanks,
K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
I'm looking through Issue #25,
https://github.com/CentreForHydrology/WDPM/issues/25
[https://avatars.githubusercontent.com/u/25204882?s=400&v=4]<https://github.com/CentreForHydrology/WDPM/issues/25>
Missing CL subdirectory · Issue #25 · CentreForHydrology/WDPM<https://github.com/CentreForHydrology/WDPM/issues/25>
Overlaps with #16, #20, and/or #23. Following the compilation instructions given in the manual here, I find that the program is missing a CL subdirectory. $ gcc WDPMCL-Command-line.c -lOpenCL -o WD...
github.com

It says

Following the compilation instructions given in the manual here<https://research-groups.usask.ca/hydrology/modelling/wdpm.php>, I find that the program is missing a CL subdirectory.

$ gcc WDPMCL-Command-line.c -lOpenCL -o WDPMCL
WDPMCL-Command-line.c:25:10: fatal error: CL/cl.h: No such file or directory
   25 | #include <CL/cl.h>
      |          ^~~~~~~~~
compilation terminated.

I know this isn't a problem any more, although the code still has this:

#ifdef __APPLE__
#include <OpenCL/opencl.h>
#include <sys/malloc.h>
#else
#include <CL/cl.h>
#endif

Just out of curiosity, where is CL defined?
I don't know much at all about C!

Thanks,

K
---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
Also, issue #19
https://github.com/CentreForHydrology/WDPM/issues/19
[https://avatars.githubusercontent.com/u/25204882?s=400&v=4]<https://github.com/CentreForHydrology/WDPM/issues/19>
Indicate dependencies · Issue #19 · CentreForHydrology/WDPM<https://github.com/CentreForHydrology/WDPM/issues/19>
I haven&#39;t seen any file indicating code dependencies. For Python, a requirements.txt file would be helpful. For other dependencies, such as gdaldem, which appears in WDPM/src/cmap_black.sh, the...
github.com


We need a Python requirements.txt file
Thanks
---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by leogean3** [comment]
Hi Kevin,

1, I generate the requirement file automatically with "pipreqs". Seems that only 'wx' is needed for python😂

2, In my Linux system, the CL header files are included under the folder "/usr/include/CL" which can be detected automatically by the compiler. I think install OpenCL on Linux add these header files to this directory by default.

3, I delete the "malloc.h" in the source C code. This header includes non-standard functions, and actually "stdlib.h" is enough to use 'malloc' in our code.

Please check.
Best regards,
Leo
________________________________
发件人: KevinShook <notifications@github.com>
发送时间: 2021年2月3日 10:16
收件人: CentreForHydrology/WDPM <WDPM@noreply.github.com>
抄送: Liu, Tonghe <tol924@mail.usask.ca>; Author <author@noreply.github.com>
主题: Re: [CentreForHydrology/WDPM] Update WDPM.py (#34)


Also, issue #19
https://github.com/CentreForHydrology/WDPM/issues/19
[https://avatars.githubusercontent.com/u/25204882?s=400&v=4]<https://github.com/CentreForHydrology/WDPM/issues/19>
Indicate dependencies · Issue #19 · CentreForHydrology/WDPM<https://github.com/CentreForHydrology/WDPM/issues/19>
I haven&#39;t seen any file indicating code dependencies. For Python, a requirements.txt file would be helpful. For other dependencies, such as gdaldem, which appears in WDPM/src/cmap_black.sh, the...
github.com


We need a Python requirements.txt file
Thanks
---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Comment by KevinShook** [comment]
Thanks very much.
Can you add the requirement file since they are asking for it,
even if it only has one library?
Thanks.
I merged your pull request. Seems to work OK.

Thanks also for your info about the file locations - that helps a lot.

K

---

Dr. Kevin Shook, P.Eng.


Research Scientist

Centre for Hydrology

Department of Geography and Planning

University of Saskatchewan

101.07 - 121 Research Drive

Saskatoon, SK

Canada

S7N 1K2

(306)966-5514

________________________________

**Pull request closed without merging**
